[python]
disabled = true
symbol = "👾 "
pyenv_version_name = true

[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

[aws]
format = "on [$symbol$region]($style) "
style = "bold blue"
symbol = "🅰 "
disabled = false

[kubernetes]
format = 'on [☸ $context \($namespace\)](dimmed yellow) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
